### ISSUE TITLE
Migrating from Mongodb to Supabase

### ISSUE THREAD

**Issue by rezteknoloji** [yesmore/inke#6]
Hi!
I want to change the database from **mongodb** to **supabase**. What and which files should i change? how to change the **schema.prisma** file and other files in order to store data in **supabase database**? 

Thank you <3

**Comment by yesmore** [comment]
The primary file you'll need to modify is `schema.prisma`. Since I have not used Supabase, I recommend referring to the official documentation at https://supabase.com/partners/integrations/prisma for instructions on making the necessary changes.
